version 0.2

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -830,6 +830,7 @@ Optional Packages:
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
   --with-sprng=/path/to/sprng
                           Location of SPRNG library
+  --with-gmp=yes          whether sprng was built with gmp (default=yes)
 
 Some influential environment variables:
   CC          C compiler command
@@ -2531,7 +2532,20 @@ fi
 
 fi
 
-echo "$as_me:$LINENO: checking for main in -lgmp" >&5
+echo "Try to find libgmp.a if we need it ..."
+
+# Check whether --with-gmp or --without-gmp was given.
+if test "${with_gmp+set}" = set; then
+  withval="$with_gmp"
+   use_gmp=${withval}
+else
+   use_gmp="yes"
+fi;
+
+if test "${use_gmp}" = "no"; then
+    echo "OK, don't need it."
+elif test "${use_gmp}" = "yes"; then
+    echo "$as_me:$LINENO: checking for main in -lgmp" >&5
 echo $ECHO_N "checking for main in -lgmp... $ECHO_C" >&6
 if test "${ac_cv_lib_gmp_main+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -2586,6 +2600,12 @@ else
    echo "libgmp not found. exiting..."; exit 1
 fi
 
+elif test -f "${use_gmp}/libgmp.a"; then
+    SPRNG_LIBS="$SPRNG_LIBS -L${use_gmp} -lgmp"
+else
+    echo "libgmp is needed but not found in specified directory ${withval}."
+    exit 1
+fi
 
 # Check whether --enable-check-pointers or --disable-check-pointers was given.
 if test "${enable_check_pointers+set}" = set; then
diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -7,7 +7,7 @@ AC_PROG_CC()
 AC_ARG_WITH(sprng,
             AC_HELP_STRING([--with-sprng=/path/to/sprng],
                            [Location of SPRNG library]),
-            [SPRNG_ROOT=${withval}],) 
+           [SPRNG_ROOT=${withval}],) 
 
 echo "Try to find sprng.h ..."
 if test -f ${SPRNG_ROOT}/include/sprng.h; then
@@ -27,8 +27,24 @@ else
                  [ echo "Cannot find libsprng"; exit 1 ])
 fi
 
-AC_CHECK_LIB(gmp,main,SPRNG_LIBS="$SPRNG_LIBS -lgmp",
-             [ echo "libgmp not found. exiting..."; exit 1 ])
+echo "Try to find libgmp.a if we need it ..."
+AC_ARG_WITH(gmp,
+            AC_HELP_STRING([--with-gmp=yes], 
+                           [whether sprng was built with gmp (default=yes)]),
+            [ use_gmp=${withval} ],
+            [ use_gmp="yes" ])
+
+if test "${use_gmp}" = "no"; then
+    echo "OK, don't need it." 
+elif test "${use_gmp}" = "yes"; then
+    AC_CHECK_LIB(gmp,main,SPRNG_LIBS="$SPRNG_LIBS -lgmp",
+                 [ echo "libgmp not found. exiting..."; exit 1 ])
+elif test -f "${use_gmp}/libgmp.a"; then
+    SPRNG_LIBS="$SPRNG_LIBS -L${use_gmp} -lgmp"
+else
+    echo "libgmp is needed but not found in specified directory ${withval}."
+    exit 1
+fi
 
 AC_ARG_ENABLE(check-pointers,
               AC_HELP_STRING([--enable-check-pointers=yes],
